GET http://localhost:8080/

###
GET http://localhost:8080/mirror_body_string
Content-Type: application/text

Hi i am body text

###
GET http://localhost:8080/mirror_body_json
Content-Type: application/json

{
    "message" : "Hello From Rest Client"
}

###
GET http://localhost:8080/path_variables/15
Content-Type: application/json

{
    "message" : "Hello From Rest Client"
}

###
GET http://localhost:8080/query_params?message=hello
Content-Type: application/json

{
    "message" : "Hello From Rest Client"
}

###
GET http://localhost:8080/header_user_agent
Content-Type: application/json
User-Agent: Rest Client User Agent


###
GET http://localhost:8080/custom_header
Content-Type: application/json
x-custom_header: Custom Header From Header