//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.6

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u64,
    pub memberable_id: Option<i32>,
    pub memberable_type: Option<String>,
    pub name: String,
    #[sea_orm(unique)]
    pub email: String,
    pub phone: Option<String>,
    pub designation: Option<String>,
    pub email_verified_at: Option<DateTimeUtc>,
    pub password: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub two_factor_secret: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub two_factor_recovery_codes: Option<String>,
    pub status: i8,
    pub last_seen: Option<DateTimeUtc>,
    pub force_logout: i8,
    pub remember_token: Option<String>,
    pub created_at: Option<DateTimeUtc>,
    pub updated_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
